# Generated by Django 5.2.11 on 2026-02-24 12:33

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilutilisateur',
            name='role',
            field=models.CharField(choices=[('SYSTEM_SUPER_ADMIN', 'Super Admin (Développeur)'), ('INSTITUTION_ADMIN', 'Admin Institution (Secrétaire Général — gestionnaire de données)'), ('MINISTRE', 'Ministre'), ('DIRECTEUR_CABINET', 'Directeur de Cabinet')], default='INSTITUTION_ADMIN', max_length=50),
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, default=core.models._default_token, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token de vérification e-mail',
                'verbose_name_plural': 'Tokens de vérification e-mail',
                'db_table': 'core_emailverificationtoken',
            },
        ),
    ]
