# Generated by Django 5.2.11 on 2026-02-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profilutilisateur_province_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='sceau_image',
            field=models.ImageField(blank=True, help_text='Sceau officiel du Ministère (PNG avec fond transparent, 300x300px)', null=True, upload_to='sceaux/'),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='signature_image',
            field=models.ImageField(blank=True, help_text='Signature scannée du Ministre (PNG avec fond transparent, 400x200px)', null=True, upload_to='signatures/'),
        ),
    ]
