# Generated by Django 5.2.11 on 2026-03-02 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_signature_sceau_fields'),
        ('gouvernance', '0015_add_agent_field_to_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='Agent du cabinet ministériel lié à ce compte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profils_utilisateur', to='gouvernance.agent'),
        ),
        migrations.AlterField(
            model_name='profilutilisateur',
            name='personne',
            field=models.ForeignKey(blank=True, help_text="DEPRECATED: Utiliser 'agent' à la place", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profils_utilisateur', to='gouvernance.personne'),
        ),
    ]
