# Generated by Django 5.2.11 on 2026-03-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_agent_field_to_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilutilisateur',
            name='role',
            field=models.CharField(choices=[('SYSTEM_SUPER_ADMIN', 'Super Admin (Développeur)'), ('INSTITUTION_ADMIN', 'Admin Institution (Secrétaire Général — gestionnaire de données)'), ('MINISTRE', 'Ministre'), ('DIRECTEUR_CABINET', 'Directeur de Cabinet'), ('DIRECTEUR_PROVINCIAL', 'Directeur (Direction provinciale)'), ('INSPECTEUR_GENERAL', 'Inspection générale'), ('FEDERATION_SECRETARY', 'Secrétaire de Fédération')], default='INSTITUTION_ADMIN', max_length=50),
        ),
    ]
