# Generated by Django 5.2.11 on 2026-03-06 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_profilutilisateur_role'),
        ('infrastructures', '0012_infrastructure_photo_stade'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='infrastructure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profils_utilisateur', to='infrastructures.infrastructure'),
        ),
        migrations.AlterField(
            model_name='profilutilisateur',
            name='role',
            field=models.CharField(choices=[('SYSTEM_SUPER_ADMIN', 'Super Admin (Développeur)'), ('INSTITUTION_ADMIN', 'Admin Institution (Secrétaire Général — gestionnaire de données)'), ('MINISTRE', 'Ministre'), ('DIRECTEUR_CABINET', 'Directeur de Cabinet'), ('DIRECTEUR_PROVINCIAL', 'Directeur (Direction provinciale)'), ('INSPECTEUR_GENERAL', 'Inspection générale'), ('FEDERATION_SECRETARY', 'Secrétaire de Fédération'), ('CLUB_SECRETARY', 'Secrétaire de Club')], default='INSTITUTION_ADMIN', max_length=50),
        ),
    ]
