# Generated by Django 5.2.11 on 2026-03-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_infra_manager_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='numero_ordre_medecins',
            field=models.CharField(blank=True, help_text="Numéro de l'Ordre des Médecins (pour le Médecin Inspecteur de la Ligue)", max_length=50),
        ),
        migrations.AlterField(
            model_name='profilutilisateur',
            name='role',
            field=models.CharField(choices=[('SYSTEM_SUPER_ADMIN', 'Super Admin (Développeur)'), ('INSTITUTION_ADMIN', 'Admin Institution (Secrétaire Général — gestionnaire de données)'), ('MINISTRE', 'Ministre'), ('DIRECTEUR_CABINET', 'Directeur de Cabinet'), ('DIRECTEUR_PROVINCIAL', 'Directeur (Direction provinciale)'), ('INSPECTEUR_GENERAL', 'Inspection générale'), ('FEDERATION_SECRETARY', 'Secrétaire de Fédération'), ('CLUB_SECRETARY', 'Secrétaire de Club'), ('INFRA_MANAGER', "Gestionnaire d'Infrastructure"), ('MEDECIN_INSPECTEUR', 'Médecin Inspecteur / Validateur')], default='INSTITUTION_ADMIN', max_length=50),
        ),
    ]
