# Generated by Django 6.0.3 on 2026-03-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_medecin_inspecteur_role_and_numero_ordre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilutilisateur',
            name='role',
            field=models.CharField(choices=[('SYSTEM_SUPER_ADMIN', 'Super Admin (Développeur)'), ('INSTITUTION_ADMIN', 'Admin Institution (Secrétaire Général — gestionnaire de données)'), ('MINISTRE', 'Ministre'), ('DIRECTEUR_CABINET', 'Directeur de Cabinet'), ('DIRECTEUR_PROVINCIAL', 'Directeur (Direction provinciale)'), ('INSPECTEUR_GENERAL', 'Inspection générale'), ('FEDERATION_SECRETARY', 'Secrétaire de Fédération'), ('LIGUE_SECRETARY', 'Secrétaire de Ligue Provinciale'), ('CLUB_SECRETARY', 'Secrétaire de Club'), ('INFRA_MANAGER', "Gestionnaire d'Infrastructure"), ('MEDECIN_INSPECTEUR', 'Médecin Inspecteur / Validateur')], default='INSTITUTION_ADMIN', max_length=50),
        ),
    ]
