# Generated by Django 6.0.3 on 2026-03-15 16:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infrastructures', '0017_add_evenement_organisateur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(blank=True, help_text='Image du QR code pour vérification', null=True, upload_to='qr_codes/tickets/')),
            ],
            options={
                'verbose_name': 'Extension Ticket',
                'verbose_name_plural': 'Extensions Tickets',
                'db_table': 'ticket_extension',
            },
        ),
        migrations.CreateModel(
            name='VenteExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_interne', models.CharField(blank=True, help_text='Référence interne pour le paiement', max_length=255)),
                ('order_number', models.CharField(blank=True, help_text='Numéro de commande FlexPay', max_length=255)),
                ('methode_paiement', models.CharField(blank=True, choices=[('MPESA', 'M-Pesa'), ('ORANGE_MONEY', 'Orange Money'), ('AIRTEL_MONEY', 'Airtel Money'), ('GUICHET', 'Guichet'), ('EN_LIGNE', 'En ligne')], help_text='Méthode de paiement utilisée', max_length=20)),
                ('telephone_payeur', models.CharField(blank=True, help_text='Téléphone du payeur', max_length=20)),
                ('statut_paiement', models.CharField(choices=[('INITIE', 'Initié'), ('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('ECHOUE', 'Échoué'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', help_text='Statut du paiement', max_length=20)),
                ('date_validation', models.DateTimeField(blank=True, help_text='Date de validation du paiement', null=True)),
                ('reference_operateur', models.CharField(blank=True, help_text="Référence de l'opérateur", max_length=255)),
                ('detail_callback', models.JSONField(blank=True, help_text='Détails du callback de paiement', null=True)),
                ('erreur_paiement', models.TextField(blank=True, help_text="Message d'erreur si paiement échoué")),
            ],
            options={
                'verbose_name': 'Extension Vente',
                'verbose_name_plural': 'Extensions Ventes',
                'db_table': 'vente_extension',
            },
        ),
        migrations.CreateModel(
            name='PaiementBillet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('methode', models.CharField(choices=[('MPESA', 'M-Pesa'), ('ORANGE', 'Orange Money'), ('AIRTEL', 'Airtel Money')], max_length=20)),
                ('telephone_payeur', models.CharField(max_length=20)),
                ('reference_interne', models.CharField(max_length=100, unique=True)),
                ('order_number', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_operateur', models.CharField(blank=True, max_length=100, null=True)),
                ('statut', models.CharField(choices=[('INITIE', 'Initié'), ('EN_ATTENTE', 'En attente'), ('VALIDATE', 'Validé'), ('ECHOUE', 'Échoué'), ('ANNULE', 'Annulé')], default='INITIE', max_length=20)),
                ('date_transaction', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('detail_reconciliation', models.JSONField(blank=True, default=dict)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement_billet', to='infrastructures.vente')),
            ],
            options={
                'verbose_name': 'Paiement de billet',
                'verbose_name_plural': 'Paiements de billets',
                'db_table': 'paiement_billet',
                'ordering': ['-date_transaction'],
            },
        ),
        migrations.CreateModel(
            name='TransactionMobileMoney',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operateur', models.CharField(choices=[('MPESA', 'M-Pesa'), ('ORANGE_MONEY', 'Orange Money'), ('AIRTEL_MONEY', 'Airtel Money')], max_length=20)),
                ('reference_operateur', models.CharField(help_text='Référence transaction opérateur', max_length=255)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('devise', models.CharField(default='CDF', max_length=3)),
                ('statut', models.CharField(choices=[('INITIE', 'Initié'), ('EN_COURS', 'En cours'), ('VALIDE', 'Validé'), ('ECHOUE', 'Échoué'), ('ANNULE', 'Annulé')], max_length=20)),
                ('date_initiation', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('reponse_api', models.JSONField(blank=True, help_text="Réponse de l'API FlexPay", null=True)),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_mm', to='infrastructures.vente')),
            ],
            options={
                'verbose_name': 'Transaction Mobile Money',
                'verbose_name_plural': 'Transactions Mobile Money',
                'db_table': 'transaction_mobile_money',
                'ordering': ['-date_initiation'],
            },
        ),
        migrations.CreateModel(
            name='VerificationQR',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hash_verification', models.CharField(help_text='Hash de vérification unique', max_length=64, unique=True)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('url_verification', models.URLField(help_text='URL de vérification publique')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_qr', to='infrastructures.ticket')),
            ],
            options={
                'verbose_name': 'Vérification QR',
                'verbose_name_plural': 'Vérifications QR',
                'db_table': 'verification_qr',
            },
        ),
    ]
