# Generated by Django 5.2.11 on 2026-03-06 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gouvernance', '0032_alter_clubvalidation_options_and_more'),
        ('infrastructures', '0002_add_infrastructure_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infrastructure',
            name='adresse_texte',
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='avenue',
            field=models.CharField(blank=True, help_text="Nom de l'avenue/rue", max_length=255),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='numero',
            field=models.CharField(blank=True, help_text='Numéro de la rue', max_length=50),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='quartier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infrastructures', to='gouvernance.groupementquartier'),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='secteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infrastructures', to='gouvernance.secteurcommune'),
        ),
    ]
