# Generated by Django 5.2.11 on 2026-03-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructures', '0003_remove_infrastructure_adresse_texte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructure',
            name='contact_gestionnaire',
            field=models.CharField(blank=True, help_text='Téléphone ou email du gestionnaire pour les réservations', max_length=255),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='gestionnaire_nom',
            field=models.CharField(blank=True, help_text="Nom du gestionnaire ou de l'organisation responsable", max_length=255),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='proprietaire_type',
            field=models.CharField(blank=True, choices=[('ETAT', 'État'), ('PROVINCE', 'Province'), ('PRIVE', 'Privé'), ('EGLISE', 'Église')], help_text="Type de propriétaire de l'infrastructure", max_length=50),
        ),
    ]
