# Generated by Django 5.2.11 on 2026-03-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructures', '0004_infrastructure_contact_gestionnaire_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infrastructure',
            name='gestionnaire',
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='proprietaire',
            field=models.CharField(blank=True, help_text="Nom du propriétaire ou de l'institution propriétaire", max_length=255),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='proprietaire_type',
            field=models.CharField(blank=True, choices=[('PRIVE', 'Privé'), ('PUBLIC', 'Public (État)')], help_text="Type de propriétaire de l'infrastructure", max_length=50),
        ),
    ]
