# Generated by Django 5.2.11 on 2026-03-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructures', '0005_remove_infrastructure_gestionnaire_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infrastructure',
            name='contact_gestionnaire',
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='email_gestionnaire',
            field=models.EmailField(blank=True, help_text='Adresse email du gestionnaire', max_length=254),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='telephone_gestionnaire',
            field=models.CharField(blank=True, help_text='Numéro de téléphone du gestionnaire', max_length=20),
        ),
    ]
