# Generated by Django 5.2.11 on 2026-03-06 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gouvernance', '0032_alter_clubvalidation_options_and_more'),
        ('infrastructures', '0006_remove_infrastructure_contact_gestionnaire_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infrastructure',
            name='gestionnaire_nom',
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='gestionnaire',
            field=models.ForeignKey(blank=True, help_text="Gestionnaire responsable de l'infrastructure", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infrastructures_gerees', to='gouvernance.personne'),
        ),
    ]
