# Generated by Django 5.2.11 on 2026-03-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructures', '0007_remove_infrastructure_gestionnaire_nom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infrastructure',
            name='gestionnaire',
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='gestionnaire_nom',
            field=models.CharField(blank=True, help_text='Nom du gestionnaire', max_length=100),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='gestionnaire_postnom',
            field=models.CharField(blank=True, help_text='Postnom du gestionnaire', max_length=100),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='gestionnaire_prenom',
            field=models.CharField(blank=True, help_text='Prénom du gestionnaire', max_length=100),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='gestionnaire_sexe',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], help_text='Sexe du gestionnaire', max_length=1),
        ),
    ]
