# Generated by Django 5.2.11 on 2026-03-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructures', '0008_remove_infrastructure_gestionnaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructure',
            name='gestionnaire_type',
            field=models.CharField(blank=True, choices=[('PERSONNE', 'Personne Physique'), ('ENTREPRISE', 'Entreprise')], help_text='Type de gestionnaire', max_length=50),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='gestionnaire_postnom',
            field=models.CharField(blank=True, help_text='Postnom du gestionnaire (pour personne physique)', max_length=100),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='gestionnaire_prenom',
            field=models.CharField(blank=True, help_text='Prénom du gestionnaire (pour personne physique)', max_length=100),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='gestionnaire_sexe',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], help_text='Sexe du gestionnaire (pour personne physique)', max_length=1),
        ),
    ]
