# Generated by Django 5.2.11 on 2026-03-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructures', '0009_infrastructure_gestionnaire_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructure',
            name='motif_rejet',
            field=models.TextField(blank=True, help_text='Motif du rejet (si applicable)'),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée')], default='EN_ATTENTE', help_text="Statut de validation de l'infrastructure", max_length=50),
        ),
    ]
