# Generated by Django 5.2.11 on 2026-03-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructures', '0010_infrastructure_motif_rejet_infrastructure_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructure',
            name='capacite_spectateurs',
            field=models.PositiveIntegerField(blank=True, help_text='Capacité en spectateurs', null=True),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='eclairage',
            field=models.CharField(blank=True, choices=[('OUI', 'Oui'), ('NON', 'Non'), ('PARTIEL', 'Partiel')], help_text="Présence d'éclairage", max_length=50),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='equipements_disponibles',
            field=models.TextField(blank=True, help_text='Liste des équipements disponibles'),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='securite',
            field=models.TextField(blank=True, help_text='Mesures de sécurité en place'),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='surface_sportive',
            field=models.CharField(blank=True, help_text='Surface sportive (ex: 100m x 60m, 50m x 25m)', max_length=100),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='vestiaires',
            field=models.CharField(blank=True, choices=[('OUI', 'Oui'), ('NON', 'Non'), ('PARTIEL', 'Partiel')], help_text='Présence de vestiaires', max_length=50),
        ),
    ]
