# Generated by Django 5.2.11 on 2026-03-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructures', '0011_infrastructure_capacite_spectateurs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructure',
            name='photo_stade',
            field=models.ImageField(blank=True, help_text='Photo du stade', null=True, upload_to='infrastructures/photos/'),
        ),
    ]
