# Generated by Django 5.2.11 on 2026-03-06 13:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructures', '0012_infrastructure_photo_stade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infrastructure',
            name='photo_stade',
        ),
        migrations.CreateModel(
            name='PhotoInfrastructure',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo', models.ImageField(help_text='Photo du stade', upload_to='infrastructures/photos/')),
                ('description', models.CharField(blank=True, help_text='Description de la photo (ex: Vue générale, Entrée, Vestiaires, etc.)', max_length=255)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('infrastructure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='infrastructures.infrastructure')),
            ],
            options={
                'verbose_name': 'Photo infrastructure',
                'verbose_name_plural': 'Photos infrastructure',
                'db_table': 'photo_infrastructure',
                'ordering': ['date_upload'],
            },
        ),
    ]
