# Generated by Django 5.2.11 on 2026-03-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructures', '0013_remove_infrastructure_photo_stade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastructure',
            name='code_homologation',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
