# Generated by Django 5.2.11 on 2026-03-09 09:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gouvernance', '0032_alter_clubvalidation_options_and_more'),
        ('infrastructures', '0014_alter_infrastructure_code_homologation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_intervention', models.DateField()),
                ('type_intervention', models.CharField(help_text='Ex: Tonte, Réparation filets, Nettoyage vestiaires', max_length=100)),
                ('description', models.TextField(help_text="Détails de l'intervention")),
                ('photo', models.ImageField(blank=True, help_text="Photo avant/après de l'intervention", null=True, upload_to='infrastructures/maintenance/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('infrastructure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='infrastructures.infrastructure')),
            ],
            options={
                'verbose_name': 'Journal de maintenance',
                'verbose_name_plural': 'Journaux de maintenance',
                'db_table': 'maintenance_log',
                'ordering': ['-date_intervention'],
            },
        ),
        migrations.CreateModel(
            name='StateChangeLog',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ancien_etat', models.CharField(max_length=50)),
                ('nouvel_etat', models.CharField(max_length=50)),
                ('justification', models.TextField(help_text="Raison du changement d'état")),
                ('photo', models.ImageField(blank=True, help_text="Photo de l'incident (si applicable)", null=True, upload_to='infrastructures/incidents/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('infrastructure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_changes', to='infrastructures.infrastructure')),
            ],
            options={
                'verbose_name': "Changement d'état",
                'verbose_name_plural': "Changements d'état",
                'db_table': 'state_change_log',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ReservationSlot',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_reservation', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('present', models.BooleanField(default=False, help_text='Club présent à la réservation')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infrastructure_reservations', to='gouvernance.institution')),
                ('infrastructure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='infrastructures.infrastructure')),
            ],
            options={
                'verbose_name': 'Créneau de réservation',
                'verbose_name_plural': 'Créneaux de réservation',
                'db_table': 'reservation_slot',
                'ordering': ['date_reservation', 'heure_debut'],
                'unique_together': {('infrastructure', 'date_reservation', 'heure_debut', 'heure_fin')},
            },
        ),
    ]
