# Generated by Django 6.0.3 on 2026-03-13 12:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_profilutilisateur_role'),
        ('infrastructures', '0015_maintenancelog_statechangelog_reservationslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(help_text="Ex: Match RDC vs Sénégal, Championnat d'athlétisme", max_length=255)),
                ('type_evenement', models.CharField(choices=[('MATCH', 'Match'), ('COMPETITION_ATHLETISME', "Compétition d'athlétisme"), ('COMPETITION', 'Compétition sportive'), ('GALA', 'Gala / Cérémonie'), ('AUTRE', 'Autre')], default='MATCH', max_length=50)),
                ('date_evenement', models.DateField()),
                ('heure_debut', models.TimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
                ('infrastructure', models.ForeignKey(help_text="Lieu (stade) de l'événement", on_delete=django.db.models.deletion.PROTECT, related_name='evenements', to='infrastructures.infrastructure')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'db_table': 'evenement',
                'ordering': ['-date_evenement', '-heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='EvenementZone',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, help_text='Prix du ticket pour cette zone (CDF)', max_digits=12)),
                ('devise', models.CharField(default='CDF', max_length=3)),
                ('capacite_max', models.PositiveIntegerField(help_text='Nombre de places (tickets) disponibles pour cette zone')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones_tarifs', to='infrastructures.evenement')),
            ],
            options={
                'verbose_name': 'Tarif zone (événement)',
                'verbose_name_plural': 'Tarifs zones (événement)',
                'db_table': 'evenement_zone',
            },
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_vente', models.DateTimeField(auto_now_add=True)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('devise', models.CharField(default='CDF', max_length=3)),
                ('canal', models.CharField(choices=[('GUICHET', 'Guichet'), ('MOBILE_MONEY', 'Mobile Money'), ('EN_LIGNE', 'En ligne'), ('AUTRE', 'Autre')], default='GUICHET', max_length=50)),
                ('reference_paiement', models.CharField(blank=True, help_text='Référence transaction (ex: Mobile Money)', max_length=255)),
                ('acheteur_nom', models.CharField(blank=True, max_length=255)),
                ('acheteur_telephone', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('caissier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes_billetterie', to='core.profilutilisateur')),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to='infrastructures.evenement')),
            ],
            options={
                'verbose_name': 'Vente (billetterie)',
                'verbose_name_plural': 'Ventes (billetterie)',
                'db_table': 'vente_billetterie',
                'ordering': ['-date_vente'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('VENDU', 'Vendu'), ('UTILISE', "Utilisé (scanné à l'entrée)"), ('ANNULE', 'Annulé')], default='DISPONIBLE', max_length=20)),
                ('date_utilisation', models.DateTimeField(blank=True, help_text="Date/heure du scan à l'entrée (anti-fraude)", null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('evenement_zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='infrastructures.evenementzone')),
                ('vente', models.ForeignKey(blank=True, help_text='Vente associée (null si pas encore vendu)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='infrastructures.vente')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'db_table': 'ticket_billetterie',
                'ordering': ['evenement_zone', 'date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ZoneStade',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(help_text="Ex: Tribune d'honneur, Tribune latérale, Pourtour", max_length=100)),
                ('ordre', models.PositiveSmallIntegerField(default=0, help_text="Ordre d'affichage")),
                ('infrastructure', models.ForeignKey(help_text='Stade concerné', on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='infrastructures.infrastructure')),
            ],
            options={
                'verbose_name': 'Zone stade',
                'verbose_name_plural': 'Zones stade',
                'db_table': 'zone_stade',
                'ordering': ['infrastructure', 'ordre', 'nom'],
                'unique_together': {('infrastructure', 'nom')},
            },
        ),
        migrations.AddField(
            model_name='evenementzone',
            name='zone_stade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evenements_tarifs', to='infrastructures.zonestade'),
        ),
        migrations.AlterUniqueTogether(
            name='evenementzone',
            unique_together={('evenement', 'zone_stade')},
        ),
    ]
