# Generated by Django 6.0.3 on 2026-03-13 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gouvernance', '0046_add_visite_medicale_uid'),
        ('infrastructures', '0016_billetterie_evenement_zone_ticket_vente'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='organisateur',
            field=models.ForeignKey(blank=True, help_text='Ligue ou fédération organisatrice (ex: ligue provinciale)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements_organises', to='gouvernance.institution'),
        ),
    ]
