# Generated by Django 6.0.3 on 2026-03-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructures', '0017_add_evenement_organisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='numero_billet',
            field=models.CharField(blank=True, editable=False, help_text='Numéro de billet visible (pour vérification manuelle)', max_length=12, null=True, unique=True),
        ),
    ]
