# Generated by Django 6.0.3 on 2026-03-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructures', '0018_ticket_numero_billet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='statut',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVE', 'Réservé (en attente de paiement)'), ('VENDU', 'Vendu'), ('UTILISE', "Utilisé (scanné à l'entrée)"), ('ANNULE', 'Annulé')], default='DISPONIBLE', max_length=20),
        ),
    ]
