# Generated by Django 6.0.3 on 2026-03-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructures', '0019_alter_ticket_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='type_evenement',
            field=models.CharField(choices=[('MATCH', 'Match'), ('COMPETITION_ATHLETISME', "Compétition d'athlétisme"), ('COMPETITION', 'Compétition sportive'), ('GALA', 'Gala / Cérémonie'), ('RESERVATION', 'Réservation privée'), ('AUTRE', 'Autre')], default='MATCH', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='statut',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_RESERVATION', 'En réservation (paiement en cours)'), ('RESERVE', 'Réservé (en attente de paiement)'), ('VENDU', 'Vendu'), ('UTILISE', "Utilisé (scanné à l'entrée)"), ('ANNULE', 'Annulé')], default='DISPONIBLE', max_length=20),
        ),
    ]
