# Generated by Django 5.2.11 on 2026-02-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gouvernance', '0003_mandat_lie_uniquement_a_membre'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='telephone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
