# Generated by Django 5.2.11 on 2026-02-24 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gouvernance', '0004_institution_niveau_territorial'),
        ('gouvernance', '0004_personne_telephone'),
    ]

    operations = [
    ]
