# Generated by Django 5.2.11 on 2026-02-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gouvernance', '0005_merge_20260224_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adressecontact',
            name='telephone',
        ),
        migrations.AddField(
            model_name='institution',
            name='logo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='institutions/logos/'),
        ),
        migrations.AddField(
            model_name='institution',
            name='statut_activation',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('INACTIF', 'Inactif')], db_index=True, default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='institution',
            name='statut_validee',
            field=models.BooleanField(default=False),
        ),
    ]
