# Generated by Django 5.2.11 on 2026-02-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gouvernance', '0006_institution_logo_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='statut_signature',
            field=models.CharField(blank=True, choices=[('', '—'), ('ATTENTE_SIGNATURE', 'En attente de signature'), ('SIGNE', 'Signé'), ('REFUSE', 'Refusé')], db_index=True, default='', max_length=30),
        ),
    ]
