# Generated by Django 5.2.11 on 2026-02-26 08:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gouvernance', '0007_institution_statut_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineSport',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('designation', models.CharField(max_length=255)),
                ('ordre', models.PositiveSmallIntegerField(default=0, help_text="Ordre d'affichage dans les listes")),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Discipline sportive',
                'verbose_name_plural': 'Disciplines sportives',
                'db_table': 'discipline_sport',
                'ordering': ['ordre', 'designation'],
            },
        ),
    ]
