# Generated by Django 5.2.11 on 2026-02-26 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gouvernance', '0008_add_discipline_sport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adressecontact',
            name='quartier_village',
        ),
        migrations.AddField(
            model_name='adressecontact',
            name='groupement_quartier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adresses', to='gouvernance.groupementquartier'),
        ),
        migrations.DeleteModel(
            name='VillageQuartier',
        ),
    ]
