# Generated by Django 5.2.11 on 2026-02-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gouvernance', '0009_remove_village_add_groupement_quartier'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='disciplines',
            field=models.ManyToManyField(blank=True, help_text='Disciplines sportives gérées par cette fédération', related_name='federations', to='gouvernance.disciplinesport'),
        ),
    ]
