# Generated by Django 5.2.11 on 2026-02-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gouvernance', '0010_institution_disciplines'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='date_demande_agrement',
            field=models.DateField(blank=True, help_text="Date de demande d'agrément", null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='document_certificat',
            field=models.FileField(blank=True, help_text='Certificat de recherche (PDF)', max_length=500, null=True, upload_to='institutions/documents/'),
        ),
        migrations.AddField(
            model_name='institution',
            name='document_liste_membres',
            field=models.FileField(blank=True, help_text='Liste des membres du comité (PDF)', max_length=500, null=True, upload_to='institutions/documents/'),
        ),
        migrations.AddField(
            model_name='institution',
            name='document_pv_ag',
            field=models.FileField(blank=True, help_text="PV de l'AG Constitutive (PDF)", max_length=500, null=True, upload_to='institutions/documents/'),
        ),
        migrations.AddField(
            model_name='institution',
            name='document_statuts',
            field=models.FileField(blank=True, help_text='Statuts de la fédération (PDF)', max_length=500, null=True, upload_to='institutions/documents/'),
        ),
        migrations.AddField(
            model_name='institution',
            name='duree_sollicitee',
            field=models.PositiveIntegerField(default=4, help_text='Durée sollicitée en années (olympiade)'),
        ),
        migrations.AddField(
            model_name='institution',
            name='nom_president',
            field=models.CharField(blank=True, help_text='Nom du Président/Mandataire', max_length=255),
        ),
        migrations.AddField(
            model_name='institution',
            name='numero_dossier',
            field=models.CharField(blank=True, help_text='Numéro de dossier interne', max_length=100),
        ),
        migrations.AddField(
            model_name='institution',
            name='site_web',
            field=models.URLField(blank=True, help_text='Site web officiel', max_length=500),
        ),
        migrations.AddField(
            model_name='institution',
            name='telephone_president',
            field=models.CharField(blank=True, help_text='Téléphone du responsable', max_length=50),
        ),
        migrations.AddField(
            model_name='institution',
            name='type_agrement_sollicite',
            field=models.CharField(blank=True, choices=[('PROVISOIRE', 'Provisoire'), ('DEFINITIF', 'Définitif')], help_text="Type d'agrément sollicité", max_length=50),
        ),
    ]
