# Generated by Django 5.2.11 on 2026-02-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gouvernance', '0011_institution_date_demande_agrement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='date_signature_arrete',
            field=models.DateTimeField(blank=True, help_text="Date et heure de signature de l'arrêté", null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='document_arrete',
            field=models.FileField(blank=True, help_text="Arrêté ministériel d'agrément (PDF)", max_length=500, null=True, upload_to='institutions/arretes/'),
        ),
        migrations.AddField(
            model_name='institution',
            name='numero_arrete',
            field=models.CharField(blank=True, help_text="Numéro de l'arrêté ministériel (ex: N°001/MIN/SL/2026)", max_length=100),
        ),
    ]
