# Generated by Django 5.2.11 on 2026-02-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gouvernance', '0012_add_arrete_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='arrete_vu_par_sg',
            field=models.BooleanField(default=False, help_text='Indique si le SG a déjà consulté cet arrêté'),
        ),
    ]
