# Generated by Django 5.2.11 on 2026-03-02 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gouvernance', '0014_add_agent_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'ordering': ['-date_enregistrement'], 'verbose_name': 'Agent', 'verbose_name_plural': 'Agents'},
        ),
        migrations.AlterField(
            model_name='agent',
            name='institution',
            field=models.ForeignKey(blank=True, help_text="Institution d'affectation", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='gouvernance.institution'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='personne',
            field=models.OneToOneField(help_text='Identité de la personne', on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='gouvernance.personne'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='sceau_image',
            field=models.ImageField(blank=True, help_text='Sceau officiel (PNG avec fond transparent)', null=True, upload_to='agents/sceaux/'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='signature_image',
            field=models.ImageField(blank=True, help_text="Signature scannée de l'agent (PNG avec fond transparent)", null=True, upload_to='agents/signatures/'),
        ),
    ]
