# Generated by Django 5.2.11 on 2026-03-02 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gouvernance', '0015_add_agent_field_to_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='province_admin',
            field=models.ForeignKey(blank=True, help_text='Province Administrative associée à cette Division Provinciale', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='divisions', to='gouvernance.provadmin'),
        ),
    ]
