# Generated by Django 5.2.11 on 2026-03-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gouvernance', '0016_add_province_admin_to_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='adressecontact',
            name='commune',
            field=models.CharField(blank=True, help_text='Commune/Ville', max_length=255),
        ),
    ]
