# Generated by Django 5.2.11 on 2026-03-02 12:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gouvernance', '0020_set_divisions_inactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='provinces_implantation',
            field=models.ManyToManyField(blank=True, help_text='Provinces où la fédération prétend être installée', related_name='federations_implantees', to='gouvernance.provadmin'),
        ),
        migrations.CreateModel(
            name='ValidationFederation',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée'), ('INCOMPLETE', 'Données incomplètes')], db_index=True, default='EN_ATTENTE', max_length=20)),
                ('existence_physique', models.BooleanField(blank=True, help_text='La fédération a-t-elle un bureau/siège dans cette province?', null=True)),
                ('activite_reelle', models.BooleanField(blank=True, help_text='Y a-t-il des athlètes, entraînements et compétitions?', null=True)),
                ('conformite_dirigeants', models.BooleanField(blank=True, help_text='Les dirigeants sont-ils crédibles et connus?', null=True)),
                ('observations', models.TextField(blank=True, help_text='Observations et commentaires du Chef de Division')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('chef_division', models.ForeignKey(blank=True, help_text='Chef de Division qui effectue la validation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations_effectuees', to='gouvernance.agent')),
                ('federation', models.ForeignKey(help_text='Fédération à valider', on_delete=django.db.models.deletion.CASCADE, related_name='validations_provinciales', to='gouvernance.institution')),
                ('province', models.ForeignKey(help_text='Province où la validation est effectuée', on_delete=django.db.models.deletion.CASCADE, related_name='validations_federations', to='gouvernance.provadmin')),
            ],
            options={
                'verbose_name': 'Validation Fédération',
                'verbose_name_plural': 'Validations Fédérations',
                'db_table': 'validation_federation',
                'ordering': ['-date_creation'],
                'unique_together': {('federation', 'province')},
            },
        ),
    ]
