# Generated by Django 5.2.11 on 2026-03-03 14:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gouvernance', '0023_add_certificate_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationLigue',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('VALIDEE', 'Validée par la Division'), ('REJETEE', 'Rejetée par la Division'), ('INCOMPLETE', 'Données incomplètes')], db_index=True, default='EN_ATTENTE', max_length=20)),
                ('clubs_existent', models.BooleanField(blank=True, help_text='Les clubs affiliés existent-ils réellement dans la province?', null=True)),
                ('structure_valide', models.BooleanField(blank=True, help_text='La structure de la ligue est-elle valide?', null=True)),
                ('dirigeants_credibles', models.BooleanField(blank=True, help_text='Les dirigeants sont-ils crédibles et connus?', null=True)),
                ('observations', models.TextField(blank=True, help_text='Observations et commentaires du Chef de Division')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('chef_division', models.ForeignKey(blank=True, help_text='Chef de Division qui effectue la validation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations_ligues_effectuees', to='gouvernance.agent')),
                ('division_provinciale', models.ForeignKey(help_text='Division Provinciale qui effectue la validation', limit_choices_to={'niveau_territorial': 'PROVINCIAL'}, on_delete=django.db.models.deletion.CASCADE, related_name='validations_ligues_effectuees', to='gouvernance.institution')),
                ('ligue', models.ForeignKey(help_text='Ligue provinciale à valider', limit_choices_to={'niveau_territorial': 'LIGUE'}, on_delete=django.db.models.deletion.CASCADE, related_name='validations_division', to='gouvernance.institution')),
            ],
            options={
                'verbose_name': 'Validation Ligue',
                'verbose_name_plural': 'Validations Ligues',
                'db_table': 'validation_ligue',
                'ordering': ['-date_creation'],
                'unique_together': {('ligue', 'division_provinciale')},
            },
        ),
        migrations.CreateModel(
            name='AttestationReconnaissance',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de validation SG'), ('APPROUVEE', 'Approuvée par le SG'), ('REJETEE', 'Rejetée par le SG')], db_index=True, default='EN_ATTENTE', max_length=20)),
                ('numero_attestation', models.CharField(blank=True, help_text="Numéro d'attestation (ex: RDC/MIN-SPORT/LIGUE/2026-001)", max_length=100, unique=True)),
                ('document_attestation', models.FileField(blank=True, help_text='Attestation de Reconnaissance (PDF)', max_length=500, null=True, upload_to='institutions/attestations/')),
                ('observations_sg', models.TextField(blank=True, help_text='Observations et commentaires du Secrétaire Général')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_approbation', models.DateTimeField(blank=True, null=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('ligue', models.ForeignKey(help_text='Ligue provinciale', limit_choices_to={'niveau_territorial': 'LIGUE'}, on_delete=django.db.models.deletion.CASCADE, related_name='attestations_reconnaissance', to='gouvernance.institution')),
                ('validation_division', models.OneToOneField(help_text='Validation de la Division Provinciale', on_delete=django.db.models.deletion.CASCADE, related_name='attestation', to='gouvernance.validationligue')),
            ],
            options={
                'verbose_name': 'Attestation de Reconnaissance',
                'verbose_name_plural': 'Attestations de Reconnaissance',
                'db_table': 'attestation_reconnaissance',
                'ordering': ['-date_creation'],
            },
        ),
    ]
