# Generated by Django 5.2.11 on 2026-03-03 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_profilutilisateur_role'),
        ('gouvernance', '0025_fix_validation_ligue_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationligue',
            name='date_transfert_division',
            field=models.DateTimeField(blank=True, help_text='Date du transfert à la Division Provinciale', null=True),
        ),
        migrations.AddField(
            model_name='validationligue',
            name='transfert_par',
            field=models.ForeignKey(blank=True, help_text='SG qui a transféré le dossier', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferts_ligues_effectues', to='core.profilutilisateur'),
        ),
        migrations.AlterField(
            model_name='validationligue',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE_SG', 'En attente - SG doit transférer'), ('EN_INSPECTION', 'En inspection - Division Provinciale'), ('INSPECTION_VALIDEE', 'Inspection validée - Retour au SG'), ('INSPECTION_REJETEE', 'Inspection rejetée - Retour au SG'), ('VALIDEE', 'Validée par la Division'), ('REJETEE', 'Rejetée par la Division'), ('INCOMPLETE', 'Données incomplètes')], db_index=True, default='EN_ATTENTE_SG', max_length=20),
        ),
    ]
