# Generated by Django 5.2.11 on 2026-03-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gouvernance', '0027_add_inspection_criteria_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='sceau_image',
            field=models.ImageField(blank=True, help_text='Cachet/Sceau de la ligue/fédération (PNG transparent)', max_length=500, null=True, upload_to='institutions/sceaux/'),
        ),
        migrations.AddField(
            model_name='institution',
            name='signature_image',
            field=models.ImageField(blank=True, help_text='Signature numérique de la ligue/fédération (PNG transparent)', max_length=500, null=True, upload_to='institutions/signatures/'),
        ),
    ]
