# Generated by Django 5.2.11 on 2026-03-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gouvernance', '0028_add_signature_sceau_to_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='document_certificat_nationalite',
            field=models.FileField(blank=True, help_text='Certificat de nationalité du responsable (PDF)', max_length=500, null=True, upload_to='institutions/documents/'),
        ),
        migrations.AddField(
            model_name='institution',
            name='document_contrat_bail',
            field=models.FileField(blank=True, help_text='Contrat de bail du club (PDF)', max_length=500, null=True, upload_to='institutions/documents/'),
        ),
        migrations.AddField(
            model_name='institution',
            name='document_liste_athletes',
            field=models.FileField(blank=True, help_text='Liste des athlètes du club (PDF)', max_length=500, null=True, upload_to='institutions/documents/'),
        ),
        migrations.AddField(
            model_name='institution',
            name='document_reglement_interieur',
            field=models.FileField(blank=True, help_text='Règlement intérieur du club (PDF)', max_length=500, null=True, upload_to='institutions/documents/'),
        ),
    ]
