# Generated by Django 5.2.11 on 2026-03-06 10:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gouvernance', '0031_club_affiliation_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubvalidation',
            options={'ordering': ['-date_demande'], 'verbose_name': 'Validation de club', 'verbose_name_plural': 'Validations de clubs'},
        ),
        migrations.AlterField(
            model_name='clubvalidation',
            name='club',
            field=models.OneToOneField(help_text='Club à valider', on_delete=django.db.models.deletion.CASCADE, related_name='validation_club', to='gouvernance.institution'),
        ),
        migrations.AlterField(
            model_name='clubvalidation',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTEE', 'Acceptée'), ('REJETEE', 'Rejetée'), ('AFFILIEE', 'Affiliée')], db_index=True, default='EN_ATTENTE', max_length=50),
        ),
        migrations.AlterField(
            model_name='clubvalidation',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
