# Generated by Django 5.2.11 on 2026-03-09 10:52

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gouvernance', '0032_alter_clubvalidation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_sportif', models.CharField(blank=True, help_text='Numéro sportif unique national (ex: RDC-ATH-2026-001234)', max_length=50, unique=True)),
                ('categorie', models.CharField(blank=True, choices=[('SENIOR', 'Senior'), ('JUNIOR', 'Junior (U20)'), ('CADET', 'Cadet (U17)'), ('MINIME', 'Minime (U15)'), ('BENJAMIN', 'Benjamin (U13)'), ('POUSSIN', 'Poussin (U11)')], default='SENIOR', help_text="Catégorie d'âge (U17, U20, Senior, etc.)", max_length=20)),
                ('poste', models.CharField(blank=True, help_text='Poste ou spécialité (ex: Gardien, Attaquant, 100m, etc.)', max_length=100)),
                ('numero_maillot', models.PositiveIntegerField(blank=True, help_text='Numéro de maillot (1-99)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('date_validite_licence', models.DateField(blank=True, help_text='Date de fin de validité de la licence sportive', null=True)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('SUSPENDU', 'Suspendu'), ('TRANSFERE', 'Transféré'), ('BLESSE', 'Blessé')], default='ACTIF', help_text="Statut actuel de l'athlète", max_length=20)),
                ('date_inscription', models.DateField(auto_now_add=True, help_text="Date d'inscription dans le club")),
                ('groupe_sanguin', models.CharField(blank=True, help_text='Groupe sanguin (A+, B-, O+, AB+, etc.)', max_length=5)),
                ('allergies', models.TextField(blank=True, help_text='Allergies connues (médicaments, aliments, etc.)')),
                ('certificat_medical', models.FileField(blank=True, help_text="Certificat médical d'aptitude à la pratique sportive", null=True, upload_to='athletes/certificats_medicaux/')),
                ('date_certificat_medical', models.DateField(blank=True, help_text='Date de délivrance du certificat médical', null=True)),
                ('aptitude_medicale', models.CharField(choices=[('APTE', 'Apte'), ('INAPTE', 'Inapte'), ('EN_ATTENTE', 'En attente de visite')], default='EN_ATTENTE', help_text='Aptitude médicale à la pratique sportive', max_length=20)),
                ('assurance_sportive', models.BooleanField(default=False, help_text='Possède une assurance sportive')),
                ('numero_assurance', models.CharField(blank=True, help_text="Numéro de police d'assurance sportive", max_length=100)),
                ('compagnie_assurance', models.CharField(blank=True, help_text="Nom de la compagnie d'assurance", max_length=200)),
                ('date_expiration_assurance', models.DateField(blank=True, help_text="Date d'expiration de l'assurance sportive", null=True)),
                ('contact_urgence_nom', models.CharField(blank=True, help_text="Nom complet du contact d'urgence", max_length=200)),
                ('contact_urgence_telephone', models.CharField(blank=True, help_text="Téléphone du contact d'urgence", max_length=20)),
                ('contact_urgence_lien', models.CharField(blank=True, help_text='Lien de parenté (père, mère, tuteur, etc.)', max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
                ('club', models.ForeignKey(blank=True, help_text="Club d'appartenance actuel", limit_choices_to={'niveau_territorial': 'CLUB'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='athletes', to='gouvernance.institution')),
                ('discipline', models.ForeignKey(blank=True, help_text='Sport/Discipline pratiquée', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='athletes', to='gouvernance.disciplinesport')),
                ('personne', models.OneToOneField(blank=True, help_text="Informations personnelles de l'athlète", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='athlete', to='gouvernance.personne')),
            ],
            options={
                'verbose_name': 'Athlète',
                'verbose_name_plural': 'Athlètes',
                'db_table': 'athlete',
                'ordering': ['personne__nom', 'personne__prenom'],
                'unique_together': {('club', 'personne')},
            },
        ),
    ]
