# Generated by Django 5.2.11 on 2026-03-10 08:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gouvernance', '0036_athlete_enrollment_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='poids',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Poids en kilogrammes (relevé lors du test médical)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AddField(
            model_name='athlete',
            name='taille',
            field=models.PositiveIntegerField(blank=True, help_text='Taille en centimètres (relevée lors du test médical)', null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='resultat_test_medical',
            field=models.CharField(choices=[('APTE', 'Apte'), ('INAPTE', 'Inapte'), ('EN_ATTENTE', 'En attente de visite')], default='EN_ATTENTE', help_text='Résultat du test médical', max_length=20),
        ),
    ]
