# Generated by Django 5.2.11 on 2026-03-10 08:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_infra_manager_role'),
        ('gouvernance', '0037_athlete_taille_poids'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisiteMedicale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_visite', models.DateField(help_text='Date de la visite médicale')),
                ('medecin_nom', models.CharField(help_text='Nom du médecin (examen provincial)', max_length=200)),
                ('medecin_etablissement', models.CharField(blank=True, help_text='Établissement ou centre de santé', max_length=255)),
                ('resultat_global', models.CharField(choices=[('APTE', 'Apte'), ('INAPTE', 'Inapte'), ('APTE_AVEC_RESERVE', 'Apte avec réserve')], default='APTE', help_text='Conclusion du médecin : Apte / Inapte / Apte avec réserve', max_length=20)),
                ('taille_cm', models.PositiveIntegerField(blank=True, help_text='Taille en cm', null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(250)])),
                ('poids_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Poids en kg', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(300)])),
                ('imc', models.DecimalField(blank=True, decimal_places=2, help_text='Indice de masse corporelle (calculé)', max_digits=5, null=True)),
                ('aptitude_cardiaque', models.BooleanField(blank=True, help_text='Auscultation cœur et poumons au repos : conforme', null=True)),
                ('tension_systolique', models.PositiveIntegerField(blank=True, help_text='Tension artérielle systolique (mmHg)', null=True, validators=[django.core.validators.MinValueValidator(80), django.core.validators.MaxValueValidator(250)])),
                ('tension_diastolique', models.PositiveIntegerField(blank=True, help_text='Tension artérielle diastolique (mmHg)', null=True, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(150)])),
                ('examen_osteo_articulaire_ok', models.BooleanField(default=True, help_text='Colonne, articulations (genoux, chevilles), souplesse : OK')),
                ('notes_examen_clinique', models.TextField(blank=True, help_text='Remarques du médecin')),
                ('ecg_joint', models.FileField(blank=True, help_text='ECG de repos (obligatoire pour prévention mort subite)', null=True, upload_to='athletes/visites_medicales/ecg/')),
                ('ecg_normal', models.BooleanField(blank=True, help_text='ECG interprété comme normal (True) ou anormal (False)', null=True)),
                ('groupe_sanguin_rh', models.CharField(blank=True, help_text='Groupe sanguin et Rhésus (ex: A+, O-) pour licence F22', max_length=10)),
                ('acuite_visuelle', models.CharField(blank=True, help_text='Acuité visuelle (ex: 10/10 OD, 10/10 OG)', max_length=100)),
                ('acuite_auditive', models.CharField(blank=True, help_text='Acuité auditive ou mention "normale"', max_length=100)),
                ('hemogramme_ok', models.BooleanField(blank=True, help_text='NFS / hémogramme complet : normal', null=True)),
                ('hemogramme_fichier', models.FileField(blank=True, null=True, upload_to='athletes/visites_medicales/hemogramme/')),
                ('examen_urines_ok', models.BooleanField(blank=True, help_text='Glycosurie / protéinurie : normal', null=True)),
                ('examen_urines_fichier', models.FileField(blank=True, null=True, upload_to='athletes/visites_medicales/urines/')),
                ('certificat_aptitude_joint', models.FileField(blank=True, help_text="Certificat d'aptitude (F72) scanné — obligatoire pour valider la licence", null=True, upload_to='athletes/visites_medicales/certificats_aptitude/')),
                ('certificat_aptitude_delivre', models.BooleanField(default=False, help_text="Certificat d'aptitude délivré (coché). Obligatoire pour validation licence.")),
                ('demande_surclassement', models.BooleanField(default=False, help_text='Demande de surclassement (ex: Cadet/Junior en Senior)')),
                ('radiographie_poignet_joint', models.FileField(blank=True, help_text='Radiographie poignet (test de Greulich et Pyle)', null=True, upload_to='athletes/visites_medicales/surclassement/')),
                ('test_greulich_pyle_ok', models.BooleanField(blank=True, help_text='Âge osseux compatible avec le surclassement', null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(help_text='Athlète concerné par cette visite', on_delete=django.db.models.deletion.CASCADE, related_name='visites_medicales', to='gouvernance.athlete')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visites_medicales_creées', to='core.profilutilisateur')),
            ],
            options={
                'verbose_name': 'Visite médicale (F67)',
                'verbose_name_plural': 'Visites médicales (F67)',
                'db_table': 'visite_medicale',
                'ordering': ['-date_visite'],
            },
        ),
    ]
