# Generated by Django 5.2.11 on 2026-03-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gouvernance', '0038_visite_medicale_f67_f72'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='aptitude_medicale',
            field=models.CharField(choices=[('APTE', 'Apte'), ('APTE_AVEC_RESERVE', 'Apte avec réserve'), ('INAPTE', 'Inapte'), ('EN_ATTENTE', 'En attente de visite')], default='EN_ATTENTE', help_text='Aptitude médicale à la pratique sportive', max_length=20),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='resultat_test_medical',
            field=models.CharField(choices=[('APTE', 'Apte'), ('APTE_AVEC_RESERVE', 'Apte avec réserve'), ('INAPTE', 'Inapte'), ('EN_ATTENTE', 'En attente de visite')], default='EN_ATTENTE', help_text='Résultat du test médical', max_length=20),
        ),
    ]
