# Generated by Django 5.2.11 on 2026-03-10 09:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_medecin_inspecteur_role_and_numero_ordre'),
        ('gouvernance', '0039_athlete_apte_avec_reserve'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedecinLigue',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_ordre_medecins', models.CharField(help_text="Numéro de l'Ordre des Médecins", max_length=50)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('agent', models.OneToOneField(help_text='Agent (Personne) enregistré comme médecin de la ligue', on_delete=django.db.models.deletion.CASCADE, related_name='medecin_ligue', to='gouvernance.agent')),
                ('ligue', models.ForeignKey(help_text='Ligue provinciale à laquelle le médecin est rattaché', limit_choices_to={'niveau_territorial__in': ['LIGUE', 'LIGUE_PROVINCIALE']}, on_delete=django.db.models.deletion.CASCADE, related_name='medecins_ligue', to='gouvernance.institution')),
                ('profil_utilisateur', models.OneToOneField(blank=True, help_text='Compte SI-SEP du médecin (créé par la Division) ; vide si pas encore de compte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medecin_ligue', to='core.profilutilisateur')),
            ],
            options={
                'verbose_name': 'Médecin de Ligue',
                'verbose_name_plural': 'Médecins de Ligue',
                'db_table': 'medecin_ligue',
                'ordering': ['ligue__nom_officiel', 'agent__personne__nom'],
            },
        ),
    ]
