# Generated by Django 5.2.11 on 2026-03-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gouvernance', '0040_medecin_ligue_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='statut_certification',
            field=models.CharField(choices=[('PROVISOIRE', 'Provisoire (En attente enrôlement Ligue)'), ('EN_ATTENTE_EXAMEN_MEDICAL', 'En attente examen médical (médecin ligue)'), ('EN_ATTENTE_VALIDATION_LIGUE', 'Enrôlé (En attente validation Ligue)'), ('CERTIFIE_PROVINCIAL', 'Certifié Provincial (En attente validation Fédération)'), ('CERTIFIE_NATIONAL', 'Certifié National (Homologué)'), ('REJETE_LIGUE', 'Rejeté par la Ligue'), ('REJETE_FEDERATION', 'Rejeté par la Fédération')], default='PROVISOIRE', help_text="Statut de certification de l'athlète dans le système", max_length=35),
        ),
    ]
