# Generated by Django 5.2.11 on 2026-03-10 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_medecin_inspecteur_role_and_numero_ordre'),
        ('gouvernance', '0041_add_en_attente_examen_medical'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptureEmpreintes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_capture', models.DateTimeField(auto_now_add=True)),
                ('main_droite_4', models.ImageField(blank=True, help_text='4 doigts main droite — posés simultanément à plat', null=True, upload_to='empreintes/%Y/%m/')),
                ('main_gauche_4', models.ImageField(blank=True, help_text='4 doigts main gauche — posés simultanément à plat', null=True, upload_to='empreintes/%Y/%m/')),
                ('pouces_2', models.ImageField(blank=True, help_text="2 pouces — posés simultanément ou l'un après l'autre", null=True, upload_to='empreintes/%Y/%m/')),
                ('athlete', models.OneToOneField(help_text='Athlète concerné', on_delete=django.db.models.deletion.CASCADE, related_name='capture_empreintes', to='gouvernance.athlete')),
                ('captured_by', models.ForeignKey(blank=True, help_text='Agent ligue ayant effectué le prélèvement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captures_empreintes', to='core.profilutilisateur')),
            ],
            options={
                'verbose_name': 'Capture d’empreintes (10 doigts)',
                'verbose_name_plural': 'Captures d’empreintes (10 doigts)',
                'db_table': 'capture_empreintes',
            },
        ),
    ]
