# Generated by Django 5.2.11 on 2026-03-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gouvernance', '0042_add_capture_empreintes'),
    ]

    operations = [
        migrations.AddField(
            model_name='captureempreintes',
            name='main_droite_4_template',
            field=models.BinaryField(blank=True, help_text='Template 4 doigts main droite — comparaison rapide et détection fraude.', null=True),
        ),
        migrations.AddField(
            model_name='captureempreintes',
            name='main_gauche_4_template',
            field=models.BinaryField(blank=True, help_text='Template 4 doigts main gauche.', null=True),
        ),
        migrations.AddField(
            model_name='captureempreintes',
            name='pouces_2_template',
            field=models.BinaryField(blank=True, help_text='Template 2 pouces.', null=True),
        ),
    ]
