# Generated by Django 5.2.11 on 2026-03-11 10:15

import django.db.models.deletion
from django.db import migrations, models


def seed_types_examen_standard_rdc(apps, schema_editor):
    """Insère les 10 examens Standard RDC dans TypeExamen."""
    TypeExamen = apps.get_model('gouvernance', 'TypeExamen')
    data = [
        {'ordre': 1,  'code': 'CARDIO',     'libelle': 'Examen Cardio-vasculaire (Auscultation du cœur)', 'obligatoire': True,  'accepte_fichier': False},
        {'ordre': 2,  'code': 'TA',          'libelle': 'Tension Artérielle (Mesure systolique/diastolique)', 'obligatoire': True,  'accepte_fichier': False},
        {'ordre': 3,  'code': 'ECG',         'libelle': 'Électrocardiogramme (ECG) — Indispensable pour la licence', 'obligatoire': True,  'accepte_fichier': True},
        {'ordre': 4,  'code': 'ACU_VIS',     'libelle': 'Acuité Visuelle (Test de vue)', 'obligatoire': True,  'accepte_fichier': False},
        {'ordre': 5,  'code': 'ACU_AUD',     'libelle': 'Acuité Auditive (Capacité à entendre les sifflets/consignes)', 'obligatoire': True,  'accepte_fichier': False},
        {'ordre': 6,  'code': 'PLEURO',      'libelle': 'Examen Pleuropulmonaire (Vérification des poumons)', 'obligatoire': True,  'accepte_fichier': False},
        {'ordre': 7,  'code': 'OSTEO',       'libelle': 'Examen Ostéo-articulaire (État des articulations et membres)', 'obligatoire': True,  'accepte_fichier': False},
        {'ordre': 8,  'code': 'NFS',         'libelle': 'Hémogramme (NFS) — Test sanguin pour l\'anémie', 'obligatoire': True,  'accepte_fichier': True},
        {'ordre': 9,  'code': 'URINES',      'libelle': 'Analyse d\'urine (Recherche de sucre ou protéines)', 'obligatoire': True,  'accepte_fichier': True},
        {'ordre': 10, 'code': 'EFFORT',      'libelle': 'Test d\'Effort (Optionnel selon la discipline)', 'obligatoire': False, 'accepte_fichier': True},
    ]
    for item in data:
        code = item['code']
        TypeExamen.objects.get_or_create(code=code, defaults=item)


def reverse_seed_types_examen(apps, schema_editor):
    TypeExamen = apps.get_model('gouvernance', 'TypeExamen')
    TypeExamen.objects.filter(code__in=[
        'CARDIO', 'TA', 'ECG', 'ACU_VIS', 'ACU_AUD', 'PLEURO', 'OSTEO', 'NFS', 'URINES', 'EFFORT'
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('gouvernance', '0043_add_empreintes_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(help_text="Intitulé du type d'examen (ex. Électrocardiogramme (ECG))", max_length=255)),
                ('code', models.CharField(blank=True, help_text='Code court optionnel (ex. ECG, NFS)', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description ou précisions pour le médecin')),
                ('obligatoire', models.BooleanField(default=True, help_text="Examen obligatoire pour la visite d'homologation")),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage dans le formulaire (plus petit = plus haut)")),
                ('actif', models.BooleanField(default=True, help_text='Inactif = masqué dans le formulaire de consultation')),
                ('accepte_fichier', models.BooleanField(default=False, help_text="Le médecin peut joindre un document pour ce type d'examen")),
            ],
            options={
                'verbose_name': "Type d'examen médical",
                'verbose_name_plural': "Types d'examens médicaux",
                'db_table': 'type_examen',
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='ResultatExamenVisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultat_ok', models.BooleanField(blank=True, help_text='Résultat conforme (True) ou non conforme (False). Null = non renseigné.', null=True)),
                ('valeur_texte', models.CharField(blank=True, help_text='Valeur textuelle (ex. 120/80 pour tension, 10/10 pour acuité)', max_length=500)),
                ('fichier', models.FileField(blank=True, help_text="Document joint si le type d'examen accepte un fichier", null=True, upload_to='athletes/visites_medicales/resultats_examens/')),
                ('visite_medicale', models.ForeignKey(help_text='Visite médicale concernée', on_delete=django.db.models.deletion.CASCADE, related_name='resultats_examens', to='gouvernance.visitemedicale')),
                ('type_examen', models.ForeignKey(help_text="Type d'examen réalisé", on_delete=django.db.models.deletion.PROTECT, related_name='resultats_visites', to='gouvernance.typeexamen')),
            ],
            options={
                'verbose_name': 'Résultat examen (visite)',
                'verbose_name_plural': 'Résultats examens (visite)',
                'db_table': 'resultat_examen_visite',
                'ordering': ['type_examen__ordre', 'type_examen__libelle'],
                'unique_together': {('visite_medicale', 'type_examen')},
            },
        ),
        migrations.RunPython(seed_types_examen_standard_rdc, reverse_seed_types_examen),
    ]
