# Generated by Django 5.2.11 on 2026-03-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gouvernance', '0044_add_type_examen_resultat_examen_visite'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitemedicale',
            name='medecin_numero_ordre',
            field=models.CharField(blank=True, help_text="Numéro d'Ordre des Médecins (traçabilité, visible par la Ligue)", max_length=50),
        ),
        migrations.AddField(
            model_name='visitemedicale',
            name='recommandations_securite',
            field=models.TextField(blank=True, help_text='Recommandations visibles par la Ligue uniquement (sécurité, équipement, ex: "Doit porter des lunettes de protection")'),
        ),
    ]
