# Generated by Django 6.0.3 on 2026-03-13 13:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gouvernance', '0046_add_visite_medicale_uid'),
        ('infrastructures', '0017_add_evenement_organisateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('saison', models.CharField(help_text='Saison / année sportive (ex: 2024-2025 ou 2024)', max_length=20)),
                ('titre', models.CharField(help_text='Titre de la compétition (ex: Championnat provincial Kinshasa 2024-2025)', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
                ('organisateur', models.ForeignKey(help_text='Ligue organisatrice', limit_choices_to={'niveau_territorial': 'LIGUE'}, on_delete=django.db.models.deletion.CASCADE, related_name='competitions_organisees', to='gouvernance.institution')),
            ],
            options={
                'verbose_name': 'Compétition',
                'verbose_name_plural': 'Compétitions',
                'db_table': 'competition',
                'ordering': ['-saison', 'titre'],
            },
        ),
        migrations.CreateModel(
            name='CalendrierCompetition',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='Date prévue')),
                ('heure_debut', models.TimeField(blank=True, null=True)),
                ('libelle', models.CharField(help_text='Ex: Journée 1, Phase de poules, Demi-finale', max_length=255)),
                ('ordre', models.PositiveSmallIntegerField(default=0, help_text='Ordre dans le calendrier')),
                ('infrastructure', models.ForeignKey(blank=True, help_text='Lieu prévu (stade/terrain)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendrier_competitions', to='infrastructures.infrastructure')),
                ('competition', models.ForeignKey(help_text='Compétition concernée', on_delete=django.db.models.deletion.CASCADE, related_name='calendrier', to='gouvernance.competition')),
            ],
            options={
                'verbose_name': 'Date du calendrier',
                'verbose_name_plural': 'Calendrier compétition',
                'db_table': 'calendrier_competition',
                'ordering': ['competition', 'date', 'ordre', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='TypeCompetition',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('designation', models.CharField(help_text='Intitulé du type (ex: Championnat provincial, Coupe de la ligue)', max_length=255)),
                ('code', models.CharField(blank=True, help_text='Code court optionnel', max_length=50)),
                ('ordre', models.PositiveSmallIntegerField(default=0, help_text="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True)),
                ('ligue', models.ForeignKey(help_text='Ligue qui enregistre ce type', limit_choices_to={'niveau_territorial': 'LIGUE'}, on_delete=django.db.models.deletion.CASCADE, related_name='types_competition', to='gouvernance.institution')),
            ],
            options={
                'verbose_name': 'Type de compétition',
                'verbose_name_plural': 'Types de compétition',
                'db_table': 'type_competition',
                'ordering': ['ligue', 'ordre', 'designation'],
                'unique_together': {('ligue', 'designation')},
            },
        ),
        migrations.AddField(
            model_name='competition',
            name='type_competition',
            field=models.ForeignKey(help_text='Type de compétition (Championnat, Coupe, etc.)', on_delete=django.db.models.deletion.PROTECT, related_name='competitions', to='gouvernance.typecompetition'),
        ),
    ]
