# Generated by Django 6.0.3 on 2026-03-13 14:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gouvernance', '0047_add_competition_type_calendrier'),
        ('infrastructures', '0017_add_evenement_organisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='categorie',
            field=models.CharField(choices=[('JUNIOR', 'Junior'), ('SENIOR', 'Sénior'), ('TOUS', 'Toutes catégories')], default='SENIOR', help_text='Catégorie (Junior, Sénior)', max_length=20),
        ),
        migrations.CreateModel(
            name='Journee',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('libelle', models.CharField(help_text='Ex: 1ère Journée, Phase de poules, Demi-finale', max_length=255)),
                ('ordre', models.PositiveSmallIntegerField(default=0, help_text="Ordre d'affichage")),
                ('competition', models.ForeignKey(help_text='Compétition concernée', on_delete=django.db.models.deletion.CASCADE, related_name='journees', to='gouvernance.competition')),
            ],
            options={
                'verbose_name': 'Journée',
                'verbose_name_plural': 'Journées',
                'db_table': 'journee',
                'ordering': ['competition', 'ordre', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='Rencontre',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_heure', models.DateTimeField(help_text='Date et heure du match')),
                ('statut', models.CharField(choices=[('PROGRAMME', 'Programmé'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('REPORTE', 'Reporté')], default='PROGRAMME', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('equipe_a', models.ForeignKey(help_text='Club (équipe A)', limit_choices_to={'niveau_territorial': 'CLUB'}, on_delete=django.db.models.deletion.PROTECT, related_name='rencontres_domicile', to='gouvernance.institution')),
                ('equipe_b', models.ForeignKey(help_text='Club (équipe B)', limit_choices_to={'niveau_territorial': 'CLUB'}, on_delete=django.db.models.deletion.PROTECT, related_name='rencontres_exterieur', to='gouvernance.institution')),
                ('evenement', models.OneToOneField(blank=True, help_text='Événement billetterie créé automatiquement pour ce match', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rencontre', to='infrastructures.evenement')),
                ('journee', models.ForeignKey(help_text='Journée ou phase', on_delete=django.db.models.deletion.CASCADE, related_name='rencontres', to='gouvernance.journee')),
                ('stade', models.ForeignKey(blank=True, help_text='Stade / infrastructure (réservation du créneau)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rencontres', to='infrastructures.infrastructure')),
            ],
            options={
                'verbose_name': 'Rencontre',
                'verbose_name_plural': 'Rencontres',
                'db_table': 'rencontre',
                'ordering': ['date_heure'],
            },
        ),
    ]
