# Generated by Django 6.0.3 on 2026-03-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gouvernance', '0049_add_audit_statut_inspection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='statut_inspection',
            field=models.CharField(blank=True, choices=[('', '—'), ('AUDIT', 'Audit'), ('ATTENTE_AGREMENT', 'Attente agrément'), ('EN_INSPECTION', 'En inspection provinciale'), ('INSPECTION_VALIDEE', 'Inspection validée'), ('INSPECTION_REJETEE', 'Inspection rejetée')], db_index=True, default='', help_text="Statut de l'inspection provinciale pour les fédérations", max_length=30),
        ),
    ]
