# Generated by Django 6.0.3 on 2026-03-20 15:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gouvernance', '0051_add_province_rendu_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arbitre',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_licence', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('niveau', models.CharField(choices=[('NATIONAL', 'National'), ('PROVINCIAL', 'Provincial'), ('LOCAL', 'Local')], default='PROVINCIAL', max_length=20)),
                ('categorie', models.CharField(choices=[('ELITE', 'Élite'), ('PREMIERE', 'Première catégorie'), ('DEUXIEME', 'Deuxième catégorie'), ('STAGIAIRE', 'Stagiaire')], default='DEUXIEME', max_length=20)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu'), ('INACTIF', 'Inactif')], default='ACTIF', max_length=20)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('discipline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='arbitres', to='gouvernance.disciplinesport')),
                ('institution', models.ForeignKey(blank=True, help_text="Ligue ou Fédération qui a enregistré l'arbitre", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arbitres', to='gouvernance.institution')),
                ('personne', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arbitre', to='gouvernance.personne')),
            ],
            options={
                'verbose_name': 'Arbitre',
                'verbose_name_plural': 'Arbitres',
                'db_table': 'arbitre',
                'ordering': ['personne__nom', 'personne__prenom'],
            },
        ),
    ]
