# Generated by Django 6.0.3 on 2026-03-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gouvernance', '0055_arbitre_niveau_categorie_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbitre',
            name='photo_droite',
            field=models.ImageField(blank=True, help_text='Profil droit', null=True, upload_to='arbitres/photos/'),
        ),
        migrations.AddField(
            model_name='arbitre',
            name='photo_gauche',
            field=models.ImageField(blank=True, help_text='Profil gauche', null=True, upload_to='arbitres/photos/'),
        ),
        migrations.AlterField(
            model_name='arbitre',
            name='categorie',
            field=models.CharField(choices=[('STAGIAIRE', 'Stagiaire'), ('ELITE', 'Élite'), ('PROFESSIONNEL', 'Professionnel')], default='DEUXIEME', max_length=20),
        ),
        migrations.AlterField(
            model_name='arbitre',
            name='empreintes_template',
            field=models.TextField(blank=True, help_text="Template d'empreintes digitales (base64 JSON)"),
        ),
        migrations.AlterField(
            model_name='arbitre',
            name='notes_medicales',
            field=models.TextField(blank=True, help_text='Observations du médecin (visibles par la ligue)'),
        ),
        migrations.AlterField(
            model_name='arbitre',
            name='photo',
            field=models.ImageField(blank=True, help_text='Photo de face', null=True, upload_to='arbitres/photos/'),
        ),
    ]
