# Generated by Django 6.0.3 on 2026-03-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gouvernance', '0056_add_arbitre_photo_profils'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbitre',
            name='main_droite_4',
            field=models.ImageField(blank=True, help_text='4 doigts main droite', null=True, upload_to='arbitres/empreintes/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='arbitre',
            name='main_droite_4_template',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arbitre',
            name='main_gauche_4',
            field=models.ImageField(blank=True, help_text='4 doigts main gauche', null=True, upload_to='arbitres/empreintes/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='arbitre',
            name='main_gauche_4_template',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arbitre',
            name='pouces_2',
            field=models.ImageField(blank=True, help_text='2 pouces', null=True, upload_to='arbitres/empreintes/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='arbitre',
            name='pouces_2_template',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arbitre',
            name='empreintes_template',
            field=models.TextField(blank=True, help_text="Template d'empreintes digitales (base64 JSON — legacy)"),
        ),
    ]
