# Generated by Django 6.0.3 on 2026-03-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gouvernance', '0057_add_arbitre_empreintes_442'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbitre',
            name='certificat_medical',
            field=models.FileField(blank=True, help_text='Certificat médical PDF généré par le médecin', null=True, upload_to='arbitres/certificats/%Y/%m/'),
        ),
    ]
